### ISSUE TITLE
! WARNING !

### ISSUE THREAD

**Issue by CrazyKoustik** [Saadkhan041/Phone_Reader#1]
The `is_valid_number()` function of the used api seems to be said (in the module documentation) to **NOT verify if the phone number is used or not**.

The used module provide functions to validate the PHONE FORMAT **ONLY**

This tool is not able to _truly_ validate phone numbers !

**Comment by Cyber-Dioxide** [comment]
Absolutely, the problem is that there is no such free API for it, with few modifications there can be added more features like career lookups.
